### ISSUE TITLE
Git tags for version

### ISSUE THREAD

**Issue by stephanlachnit** [jrmadsen/PTL#6]
I want to package this for Debian. For this workflow, git tags make my life much easier.

However, even though there is a `VERSION` file which keeps track of a version, there are no version specific git tags. It would be nice if that could be done.

**Comment by jrmadsen** [comment]
Hi @stephanlachnit yes, this is definitely an oversight. I started on this and then got sidetracked by another project. Should have it done in the next day or so, just working on changelog.
